/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 * Ventana principal que contiene las opciones que el usuario podra visualizar en el sistema SIGED.
 * @author Cristian Alexis Alegria C.
 * @version 1.0.0
 * @since SIGED 1.0.0
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Inicializa los componentes que conforman la ventana principal.
     * @since SIGED 1.0.0
     */
    public FrmPrincipal() {
        initComponents();
        iniciarFrmPrincipal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dstContenedorPrincipal = new javax.swing.JDesktopPane();
        mnbOpciones = new javax.swing.JMenuBar();
        mnuIngresar = new javax.swing.JMenu();
        mniLogueoAdministrador = new javax.swing.JMenuItem();
        mniLogueoEstudiante = new javax.swing.JMenuItem();
        mnuAdministracion = new javax.swing.JMenu();
        mniModificarContraseniaAdministrador = new javax.swing.JMenuItem();
        mniCargarArchivos = new javax.swing.JMenuItem();
        mniBuscar = new javax.swing.JMenuItem();
        mnuEstudiante = new javax.swing.JMenu();
        mniModificarContraseniaEstudiante = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dstContenedorPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout dstContenedorPrincipalLayout = new javax.swing.GroupLayout(dstContenedorPrincipal);
        dstContenedorPrincipal.setLayout(dstContenedorPrincipalLayout);
        dstContenedorPrincipalLayout.setHorizontalGroup(
            dstContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        dstContenedorPrincipalLayout.setVerticalGroup(
            dstContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        mnuIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoLogin.png"))); // NOI18N
        mnuIngresar.setText("Ingresar");

        mniLogueoAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoAdministrador.png"))); // NOI18N
        mniLogueoAdministrador.setText("Administrador");
        mnuIngresar.add(mniLogueoAdministrador);

        mniLogueoEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoEstudiante.png"))); // NOI18N
        mniLogueoEstudiante.setText("Estudiante");
        mnuIngresar.add(mniLogueoEstudiante);

        mnbOpciones.add(mnuIngresar);

        mnuAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoAdministracion.png"))); // NOI18N
        mnuAdministracion.setText("Administracion");

        mniModificarContraseniaAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoModificarContraseña.png"))); // NOI18N
        mniModificarContraseniaAdministrador.setText("Modificar Contraseña");
        mnuAdministracion.add(mniModificarContraseniaAdministrador);

        mniCargarArchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoSubirArchivo.png"))); // NOI18N
        mniCargarArchivos.setText("Cargar Archivos Planos");
        mnuAdministracion.add(mniCargarArchivos);

        mniBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoBuscar.png"))); // NOI18N
        mniBuscar.setText("Buscar");
        mnuAdministracion.add(mniBuscar);

        mnbOpciones.add(mnuAdministracion);

        mnuEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoEstudianteLogueado.png"))); // NOI18N
        mnuEstudiante.setText("Estudiante");

        mniModificarContraseniaEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoModificarContraseña.png"))); // NOI18N
        mniModificarContraseniaEstudiante.setText("Modificar Contrasenia");
        mnuEstudiante.add(mniModificarContraseniaEstudiante);

        mnbOpciones.add(mnuEstudiante);

        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoSalir.png"))); // NOI18N
        mnbOpciones.add(mnuSalir);

        setJMenuBar(mnbOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dstContenedorPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dstContenedorPrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
   /**
     * Da un nombre a la ventana principal.<br>
     * Maximiza la ventana principal a la pantalla de la computadora.<br>
     * Deshabilita  todas las opciones de la ventana principal menos la  opcion de ingresar.<br>
     * Asignar nombres especificos a cada comando de accion a las opciones de la ventana principal.
     * @since SIGED 1.0.0
     */
    
    private void iniciarFrmPrincipal(){
        setTitle("Sistema de Gestion de Encuestas a Docentes(SIGED)");     
        setExtendedState(FrmPrincipal.MAXIMIZED_BOTH);//estado maximizado
        deshabilitarOpcionesDeFrmPrincipal();
        setComandosDeAccionFrmPrincipal();
             
    }
    
    /*
     * Deshabilita  todas las opciones de la ventana principal menos la  opcion de ingresar.<br>     * 
     * @since SIGED 1.0.0
     */
    private void deshabilitarOpcionesDeFrmPrincipal(){
        getMnuAdministracion().setEnabled(false);
        getMnuEstudiante().setEnabled(false);
        getMnuSalir().setEnabled(false);       
    }
    
    /*
     * Asignar nombres especificos a cada comando de accion a las opciones de la ventana principal.
     * @since SIGED 1.0.0
     */
    private void setComandosDeAccionFrmPrincipal(){
        getMniLogueoAdministrador().setActionCommand("LogueoAdministrador");
        getMniLogueoEstudiante().setActionCommand("LogueoEstudiante");  
        getMniModificarContraseniaAdministrador().setActionCommand("ModificarContrasenia");
        getMniModificarContraseniaEstudiante().setActionCommand("ModificarContrasenia");  
        getMniCargarArchivos().setActionCommand("CargarArchivoPlano");
        getMniBuscar().setActionCommand("Consultar");     
    }
    
    
    /**
     * Metodo que retorna el contenedor principal encargado de contener todas las ventanas del sistema SIGED.
     * @return El contenedor principal del sistema SIGED.
     * @since SIGED 1.0.0
     */
    public JDesktopPane getDstContenedorPrincipal() {
        return dstContenedorPrincipal;
    }

    public void setDstContenedorPrincipal(JDesktopPane dstContenedorPrincipal) {
        this.dstContenedorPrincipal = dstContenedorPrincipal;
    }

   

    public JMenuItem getMniLogueoAdministrador() {
        return mniLogueoAdministrador;
    }

    public void setMniLogueoAdministrador(JMenuItem mniLogueoAdministrador) {
        this.mniLogueoAdministrador = mniLogueoAdministrador;
    }

    public JMenuItem getMniLogueoEstudiante() {
        return mniLogueoEstudiante;
    }

    public void setMniLogueoEstudiante(JMenuItem mniLogueoEstudiante) {
        this.mniLogueoEstudiante = mniLogueoEstudiante;
    }

    public JMenu getMnuIngresar() {
        return mnuIngresar;
    }

    public void setMnuIngresar(JMenu mnuIngresar) {
        this.mnuIngresar = mnuIngresar;
    }  

    public JMenuItem getMniModificarContraseniaAdministrador() {
        return mniModificarContraseniaAdministrador;
    }

    public void setMniModificarContraseniaAdministrador(JMenuItem mniModificarContraseniaAdministrador) {
        this.mniModificarContraseniaAdministrador = mniModificarContraseniaAdministrador;
    }   

    public JMenu getMnuAdministracion() {
        return mnuAdministracion;
    }

    public void setMnuAdministracion(JMenu mnuAdministracion) {
        this.mnuAdministracion = mnuAdministracion;
    }

    public JMenu getMnuEstudiante() {
        return mnuEstudiante;
    }

    public void setMnuEstudiante(JMenu mnuEstudiante) {
        this.mnuEstudiante = mnuEstudiante;
    }

    public JMenuItem getMniModificarContraseniaEstudiante() {
        return mniModificarContraseniaEstudiante;
    }

    public void setMniModificarContraseniaEstudiante(JMenuItem mniModificarContraseniaEstudiante) {
        this.mniModificarContraseniaEstudiante = mniModificarContraseniaEstudiante;
    }

    public JMenu getMnuSalir() {
        return mnuSalir;
    }

    public void setMnuSalir(JMenu mnuSalir) {
        this.mnuSalir = mnuSalir;
    }

    public JMenuItem getMniCargarArchivos() {
        return mniCargarArchivos;
    }

    public void setMniCargarArchivos(JMenuItem mniCargarArchivos) {
        this.mniCargarArchivos = mniCargarArchivos;
    }

    public JMenuItem getMniBuscar() {
        return mniBuscar;
    }

    public void setMniBuscar(JMenuItem mniBuscar) {
        this.mniBuscar = mniBuscar;
    }

    public JMenuBar getMnbOpciones() {
        return mnbOpciones;
    }

    public void setMnbOpciones(JMenuBar mnbOpciones) {
        this.mnbOpciones = mnbOpciones;
    }  
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dstContenedorPrincipal;
    private javax.swing.JMenuBar mnbOpciones;
    private javax.swing.JMenuItem mniBuscar;
    private javax.swing.JMenuItem mniCargarArchivos;
    private javax.swing.JMenuItem mniLogueoAdministrador;
    private javax.swing.JMenuItem mniLogueoEstudiante;
    private javax.swing.JMenuItem mniModificarContraseniaAdministrador;
    private javax.swing.JMenuItem mniModificarContraseniaEstudiante;
    private javax.swing.JMenu mnuAdministracion;
    private javax.swing.JMenu mnuEstudiante;
    private javax.swing.JMenu mnuIngresar;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
