/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 * Ventana que permite al usuario cargar achivo plano al  sistema SIGED.
 * @author Cristian Alexis Alegria C.
 * @version 1.0.0
 * @since SIGED 1.0.0
 */
public class InfCargarArchivos extends javax.swing.JInternalFrame {

   
    
    
    private JFileChooser fchBuscadorArchivo;
    
    public InfCargarArchivos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        lblCargarDocentes = new javax.swing.JLabel();
        lblCargarEstudiantes = new javax.swing.JLabel();
        lblTituloCargaArchivos = new javax.swing.JLabel();
        lblMensajeAceptar = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(866, 450));

        lblCargarDocentes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCargarDocentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoDocentes.png"))); // NOI18N
        lblCargarDocentes.setText("Cargar Docentes ");

        lblCargarEstudiantes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCargarEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoEstudiantes.png"))); // NOI18N
        lblCargarEstudiantes.setText("Cargar Estudiantes");

        lblTituloCargaArchivos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTituloCargaArchivos.setText("Cargar Archivos Txt");

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(lblMensajeAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenedorLayout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenedorLayout.createSequentialGroup()
                        .addComponent(lblCargarDocentes)
                        .addGap(91, 91, 91)
                        .addComponent(lblCargarEstudiantes)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenedorLayout.createSequentialGroup()
                        .addComponent(lblTituloCargaArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(289, 289, 289))))
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenedorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTituloCargaArchivos)
                .addGap(101, 101, 101)
                .addGroup(pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCargarEstudiantes)
                    .addComponent(lblCargarDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(lblMensajeAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public JFileChooser getFchBuscadorArchivo() {
        return fchBuscadorArchivo;
    }

    public void setFchBuscadorArchivo(JFileChooser fchBuscadorArchivo) {
        this.fchBuscadorArchivo = fchBuscadorArchivo;
    }

    public JLabel getLblCargarDocentes() {
        return lblCargarDocentes;
    }

    public void setLblCargarDocentes(JLabel lblCargarDocentes) {
        this.lblCargarDocentes = lblCargarDocentes;
    }

    public JLabel getLblCargarEstudiantes() {
        return lblCargarEstudiantes;
    }

    public void setLblCargarEstudiantes(JLabel lblCargarEstudiantes) {
        this.lblCargarEstudiantes = lblCargarEstudiantes;
    }

    public JLabel getLblMensajeAceptar() {
        return lblMensajeAceptar;
    }

    public void setLblMensajeAceptar(JLabel lblMensajeAceptar) {
        this.lblMensajeAceptar = lblMensajeAceptar;
    }

    public JLabel getLblTituloCargaArchivos() {
        return lblTituloCargaArchivos;
    }

    public void setLblTituloCargaArchivos(JLabel lblTituloCargaArchivos) {
        this.lblTituloCargaArchivos = lblTituloCargaArchivos;
    }

    public JPanel getPnlContenedor() {
        return pnlContenedor;
    }

    public void setPnlContenedor(JPanel pnlContenedor) {
        this.pnlContenedor = pnlContenedor;
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCargarDocentes;
    private javax.swing.JLabel lblCargarEstudiantes;
    private javax.swing.JLabel lblMensajeAceptar;
    private javax.swing.JLabel lblTituloCargaArchivos;
    private javax.swing.JPanel pnlContenedor;
    // End of variables declaration//GEN-END:variables
}
